"""Configurable presentation of structured TPStudio diagnostics."""

from .models import FeedbackAudience, FeedbackPriority
from .quantity import (
    QuantityFeedbackCatalog,
    QuantityFeedbackItem,
    QuantityFeedbackRenderer,
    QuantityFeedbackSet,
    QuantityFeedbackTemplate,
    french_quantity_feedback_catalog,
    render_quantity_feedback,
)
from .quantity_comparisons import (
    QuantityComparisonFeedbackCatalog,
    QuantityComparisonFeedbackItem,
    QuantityComparisonFeedbackRenderer,
    QuantityComparisonFeedbackSet,
    QuantityComparisonFeedbackTemplate,
    french_quantity_comparison_feedback_catalog,
    render_quantity_comparison_feedback,
)
from .comparison_interpretations import (
    ComparisonInterpretationFeedbackCatalog,
    ComparisonInterpretationFeedbackItem,
    ComparisonInterpretationFeedbackRenderer,
    ComparisonInterpretationFeedbackSet,
    ComparisonInterpretationFeedbackTemplate,
    french_comparison_interpretation_feedback_catalog,
    render_comparison_interpretation_feedback,
)
from .comparison_justifications import (
    ComparisonJustificationFeedbackCatalog,
    ComparisonJustificationFeedbackItem,
    ComparisonJustificationFeedbackRenderer,
    ComparisonJustificationFeedbackSet,
    ComparisonJustificationFeedbackTemplate,
    ComparisonJustificationFeedbackVariant,
    comparison_justification_feedback_variant,
    french_comparison_justification_feedback_catalog,
    render_comparison_justification_feedback,
)

__all__ = [
    "ComparisonInterpretationFeedbackCatalog",
    "ComparisonInterpretationFeedbackItem",
    "ComparisonInterpretationFeedbackRenderer",
    "ComparisonInterpretationFeedbackSet",
    "ComparisonInterpretationFeedbackTemplate",
    "ComparisonJustificationFeedbackCatalog",
    "ComparisonJustificationFeedbackItem",
    "ComparisonJustificationFeedbackRenderer",
    "ComparisonJustificationFeedbackSet",
    "ComparisonJustificationFeedbackTemplate",
    "ComparisonJustificationFeedbackVariant",
    "FeedbackAudience",
    "FeedbackPriority",
    "QuantityFeedbackCatalog",
    "QuantityComparisonFeedbackCatalog",
    "QuantityComparisonFeedbackItem",
    "QuantityComparisonFeedbackRenderer",
    "QuantityComparisonFeedbackSet",
    "QuantityComparisonFeedbackTemplate",
    "QuantityFeedbackItem",
    "QuantityFeedbackRenderer",
    "QuantityFeedbackSet",
    "QuantityFeedbackTemplate",
    "french_quantity_feedback_catalog",
    "french_comparison_interpretation_feedback_catalog",
    "french_comparison_justification_feedback_catalog",
    "french_quantity_comparison_feedback_catalog",
    "render_quantity_feedback",
    "render_comparison_interpretation_feedback",
    "render_comparison_justification_feedback",
    "comparison_justification_feedback_variant",
    "render_quantity_comparison_feedback",
]
