from __future__ import annotations
from tpstudio.pedagogical_sections import add_pedagogical_section_feedback_to_report

from pathlib import Path

from tpstudio.copy_comparison import compare_copy_to_model
from tpstudio.copy_feedback import structured_feedback_markdown


def _tpstudio_original_export_feedback_report_a61a(
    model_path: str | Path,
    copy_path: str | Path,
    output_path: str | Path | None = None,
) -> Path:
    """Export a Markdown feedback report for one student copy.

    This report is text-based and complements the annotated notebook generated by
    feedback-copy. It is meant to be easy to archive, read, diff, and later parse
    for group summaries.
    """

    model = Path(model_path)
    copy = Path(copy_path)

    if output_path is None:
        output = _next_available_report_path(copy)
    else:
        output = Path(output_path)

    comparison = compare_copy_to_model(model, copy)
    markdown = format_feedback_report_markdown(comparison)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(markdown, encoding="utf-8")
    return output


def format_feedback_report_markdown(comparison) -> str:
    """Return a Markdown report for a copy comparison."""

    body = structured_feedback_markdown(comparison)

    lines = [
        "# Rapport TPStudio",
        "",
        f"- Modèle : `{Path(comparison.model_path).name}`",
        f"- Copie : `{Path(comparison.copy_path).name}`",
        "",
        body,
        "",
    ]

    return "\n".join(lines)


def _next_available_report_path(copy_path: Path) -> Path:
    base = copy_path.with_name(copy_path.stem + "-rapport-tpstudio.md")
    if not base.exists():
        return base

    counter = 2
    while True:
        candidate = copy_path.with_name(copy_path.stem + f"-rapport-tpstudio-{counter}.md")
        if not candidate.exists():
            return candidate
        counter += 1

def export_feedback_report(
    model_path,
    copy_path,
    output_path=None,
):
    if output_path is None:
        result = _tpstudio_original_export_feedback_report_a61a(
            model_path,
            copy_path,
        )
        report_path = result
    else:
        result = _tpstudio_original_export_feedback_report_a61a(
            model_path,
            copy_path,
            output_path,
        )
        report_path = result if result is not None else output_path

    add_pedagogical_section_feedback_to_report(
        copy_path,
        report_path,
    )
    return result

