from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path


CONSIGNES_RAPPORT_URL = "https://www.pcsi2.net/fabert/wp-content/uploads/physique/Consignes-de-redaction-dun-rapport.pdf"

REPORT_IDENTITY_MARKER = "tpstudio_report_identity"


@dataclass(frozen=True)
class NotebookPostprocessResult:
    path: Path
    changed: bool
    identity_inserted: bool
    duplicate_generated_cells_removed: int


def report_identity_markdown() -> str:
    return (
        "## Identification du compte rendu\n"
        "\n"
        "**Noms :**  \n"
        "**Groupe :**  \n"
        "**Date de la séance :**  \n"
        "\n"
        "Ce notebook fait office de rapport de TP. Il doit répondre aux attentes "
        "précisées dans l'annexe "
        f"[Consignes de rédaction d'un rapport de TP]({CONSIGNES_RAPPORT_URL}).\n"
    )


def report_identity_cell() -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {
            "tpstudio": {
                "cell_role": "report_identity",
                "marker": REPORT_IDENTITY_MARKER,
            }
        },
        "source": report_identity_markdown().splitlines(keepends=True),
    }


def postprocess_improved_notebook(notebook_path: str | Path) -> NotebookPostprocessResult:
    """Clean and normalize a notebook generated by ``tpstudio improve``.

    This function is intentionally idempotent:
    - it inserts the report identity cell only if missing;
    - it keeps only one TPStudio improvement block;
    - it keeps only one TPStudio competency-evaluation block.
    """

    path = Path(notebook_path)
    data = json.loads(path.read_text(encoding="utf-8"))

    cells = data.setdefault("cells", [])
    if not isinstance(cells, list):
        cells = []
        data["cells"] = cells

    changed = False

    cells, removed = _remove_duplicate_generated_cells(cells)
    # _remove_duplicate_generated_cells returns a new list.
    # Always reattach it before inserting the identity cell; otherwise the
    # insertion can be done on a detached list and not be saved to disk.
    data["cells"] = cells

    if removed:
        changed = True

    identity_inserted = False
    if not has_report_identity_cell(cells):
        insertion_index = _report_identity_insertion_index(cells)
        cells.insert(insertion_index, report_identity_cell())
        identity_inserted = True
        changed = True

    if changed:
        metadata = data.setdefault("metadata", {})
        if isinstance(metadata, dict):
            tpstudio = metadata.setdefault("tpstudio", {})
            if isinstance(tpstudio, dict):
                tpstudio["report_identity_cell_inserted"] = True
                tpstudio["generated_sections_deduplicated"] = True
                tpstudio["improve_postprocessed"] = True

        path.write_text(json.dumps(data, ensure_ascii=False, indent=1), encoding="utf-8")

    return NotebookPostprocessResult(
        path=path,
        changed=changed,
        identity_inserted=identity_inserted,
        duplicate_generated_cells_removed=removed,
    )


def postprocess_improved_notebooks_in_target(target: str | Path) -> list[NotebookPostprocessResult]:
    """Post-process notebooks under a file or directory target.

    The function is deliberately permissive because ``improve`` may be run on an
    already improved notebook, a folder, or a test copy. It only touches notebooks
    that look like TPStudio improved notebooks or that contain TPStudio generated
    sections.
    """

    path = Path(target).expanduser()

    if path.is_file():
        if path.suffix == ".ipynb" and _should_postprocess_notebook(path):
            return [postprocess_improved_notebook(path)]
        return []

    if not path.exists():
        return []

    results: list[NotebookPostprocessResult] = []

    for notebook_path in sorted(path.rglob("*.ipynb")):
        if not _should_postprocess_notebook(notebook_path):
            continue

        results.append(postprocess_improved_notebook(notebook_path))

    return results


# Backward-compatible name used by A42a's first CLI wrapper.
def ensure_report_identity_cells_in_improved_notebooks(target: str | Path) -> int:
    results = postprocess_improved_notebooks_in_target(target)
    return sum(1 for result in results if result.changed)


def ensure_report_identity_cell(notebook_path: str | Path) -> bool:
    result = postprocess_improved_notebook(notebook_path)
    return result.identity_inserted


def has_report_identity_cell(cells: list[dict]) -> bool:
    for cell in cells:
        if not isinstance(cell, dict):
            continue

        metadata = cell.get("metadata", {})
        if isinstance(metadata, dict):
            tpstudio = metadata.get("tpstudio", {})
            if isinstance(tpstudio, dict):
                if tpstudio.get("marker") == REPORT_IDENTITY_MARKER:
                    return True
                if tpstudio.get("cell_role") == "report_identity":
                    return True

        source = _cell_text(cell)
        normalized = _normalize_identity_source(source)

        if "tpstudio_report_identity" in normalized:
            return True

        if "identification du compte rendu" in normalized:
            return True

        has_name = "noms" in normalized or "nom" in normalized
        has_group = "groupe" in normalized
        has_date = "date de la seance" in normalized or "date seance" in normalized

        if has_name and has_group and has_date:
            return True

    return False


def _normalize_identity_source(source: str) -> str:
    normalized = source.lower()
    normalized = normalized.replace("*", "")
    normalized = normalized.replace("_", "")
    normalized = normalized.replace(":", " ")
    normalized = normalized.replace("\u00a0", " ")

    accents = {
        "é": "e",
        "è": "e",
        "ê": "e",
        "ë": "e",
        "à": "a",
        "â": "a",
        "ä": "a",
        "î": "i",
        "ï": "i",
        "ô": "o",
        "ö": "o",
        "ù": "u",
        "û": "u",
        "ü": "u",
        "ç": "c",
    }

    for accented, replacement in accents.items():
        normalized = normalized.replace(accented, replacement)

    return " ".join(normalized.split())


def _remove_duplicate_generated_cells(cells: list[dict]) -> tuple[list[dict], int]:
    seen_generated_kinds: set[str] = set()
    cleaned_cells: list[dict] = []
    removed = 0

    for cell in cells:
        kind = _generated_cell_kind(cell)

        if kind and kind in seen_generated_kinds:
            removed += 1
            continue

        if kind:
            seen_generated_kinds.add(kind)

        cleaned_cells.append(cell)

    return cleaned_cells, removed


def _generated_cell_kind(cell: dict) -> str:
    source = _cell_text(cell).lower()

    if "améliorations proposées par tpstudio" in source:
        return "tpstudio_improvements"

    if "ameliorations proposées par tpstudio" in source:
        return "tpstudio_improvements"

    if "amélioration proposées par tpstudio" in source:
        return "tpstudio_improvements"

    if "amelioration proposées par tpstudio" in source:
        return "tpstudio_improvements"

    if "évaluation par compétences" in source:
        return "tpstudio_competency_evaluation"

    if "evaluation par compétences" in source:
        return "tpstudio_competency_evaluation"

    if "evaluation par competences" in source:
        return "tpstudio_competency_evaluation"

    return ""


def _report_identity_insertion_index(cells: list[dict]) -> int:
    pdf_index = _pdf_link_cell_index(cells)
    if pdf_index is not None:
        return pdf_index + 1

    if not cells:
        return 0

    first = cells[0]
    if isinstance(first, dict) and first.get("cell_type") == "markdown":
        first_text = _cell_text(first)
        if first_text.lstrip().startswith("#") or "<h1" in first_text.lower():
            return 1

    return 0


def _pdf_link_cell_index(cells: list[dict]) -> int | None:
    for index, cell in enumerate(cells):
        source = _cell_text(cell).lower()

        if "pdf complet" in source:
            return index

        if "](" in source and ".pdf" in source:
            return index

        if "http" in source and ".pdf" in source:
            return index

    return None


def _should_postprocess_notebook(path: Path) -> bool:
    if path.name.startswith("."):
        return False

    stem = path.stem.lower()

    filename_markers = [
        "ameliore",
        "amélioré",
        "amelioree",
        "améliorée",
    ]

    if any(marker in stem for marker in filename_markers):
        return True

    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return False

    cells = data.get("cells", [])
    if not isinstance(cells, list):
        return False

    return any(_generated_cell_kind(cell) for cell in cells if isinstance(cell, dict))


def _cell_text(cell: dict) -> str:
    source = cell.get("source", "")

    if isinstance(source, list):
        return "".join(str(part) for part in source)

    return str(source)
